name: Delete Hint Comments and Push

on:
  push:
    branches:
      - main

jobs:
  delete-hint-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run delete_hint_comments.sh
        run: bash ./delete_hint_comments.sh

      - name: Commit changes
        run: |
          if ! git diff --quiet; then
            git add Checklist/Checklist.lean
            git commit -m "Delete hint comments from Checklist.lean"
          fi

      - name: Push to checklist branch
        if: success()
        run: |
          git push --force origin HEAD:checklist
